services:
  workspace:
    image: echoing/workspace:latest
    container_name: echoing-workspace
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps:/app/apps
      - ./packages:/app/packages
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./turbo.json:/app/turbo.json
      - 'workspace:/app'
    environment:
      - NODE_ENV=development
  dapr:
    image: 'daprio/dapr'
    container_name: echoing-dapr
    command: ['./placement', '-port', '50000']
    networks:
      - echoing
  content-service:
    image: node:20-alpine3.21
    container_name: echoing-content-service
    depends_on:
      - workspace
      - dapr
    working_dir: /app
    command: >
      sh -c "corepack enable && yarn workspace @echoing/content-service dev"
    environment:
      - NODE_ENV=development
      - HTTP_PORT=8080
    ports:
      - '3100:8080'
    networks:
      - echoing
    volumes_from:
      - workspace
  farewell-service:
    image: node:20-alpine3.21
    container_name: echoing-farewell-service
    depends_on:
      - workspace
      - dapr
    working_dir: /app
    command: >
      sh -c "corepack enable && yarn workspace @echoing/farewell-service dev"
    environment:
      - NODE_ENV=development
      - HTTP_PORT=8080
    ports:
      - '3101:8080'
    networks:
      - echoing
    volumes_from:
      - workspace
  greeter-service:
    image: node:20-alpine3.21
    container_name: echoing-greeter-service
    depends_on:
      - workspace
      - dapr
    working_dir: /app
    command: >
      sh -c "corepack enable && yarn workspace @echoing/greeter-service dev"
    environment:
      - NODE_ENV=development
      - HTTP_PORT=8080
    ports:
      - '3102:8080'
    networks:
      - echoing
    volumes_from:
      - workspace

networks:
  echoing:
    driver: bridge

volumes:
  workspace:
